name: "Home Cost"
version: "1.0.4"
slug: "home_cost"
description: "Aplicație pentru managementul facturilor, analiză costuri și consum, asistată de AI"
url: "https://github.com/vlad2939/ha-homecost-addon"
webui: "http://[HOST]:[PORT:3000]"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
ports:
  3000/tcp: 3003
map:
  - share:rw
options: {}
schema: {}
